---
deployment:
  tasks:
    # Pull the latest changes from the main branch
    - git pull origin main

    # Sync all files from `repositories/Ganga-Aarti` to `Ganga-Aarti`, excluding the `static` directory
    - rsync -avz --exclude='static/' --exclude='.*' ./repositories/Ganga-Aarti/ ~/Ganga-Aarti/

    # Sync files from the `static` directory in `repositories/Ganga-Aarti` to `public_html/static`
    - rsync -avz --exclude='.*' ./repositories/Ganga-Aarti/static/ ~/public_html/static/

    # Log deployment information
    - echo "Deployment Time: $(date)" > ~/deployment-info.txt
    - echo "Commit SHA: $(git rev-parse HEAD)" >> ~/deployment-info.txt
    - echo "Author: $(git log -1 --pretty=format:'%an')" >> ~/deployment-info.txt
    - echo "Commit Date: $(git log -1 --pretty=format:'%ad')" >> ~/deployment-info.txt
    - echo "Commit Message: $(git log -1 --pretty=format:'%s')" >> ~/deployment-info.txt


